# Generated by Django 5.1.3 on 2024-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_schoolclass_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
