# Generated by Django 5.1.3 on 2024-11-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.schoolclass'),
        ),
    ]
