# Generated by Django 5.1.3 on 2024-11-29 10:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_exam_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('stops', models.TextField(blank=True, help_text='List the stops along the route')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='BusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(blank=True, max_length=100)),
                ('dropoff_point', models.CharField(blank=True, max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='users.busroute'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
    ]
