# Generated by Django 5.1.3 on 2024-11-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_timetable_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
