# Generated by Django 5.1.3 on 2024-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_discount_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='class_group',
            field=models.CharField(blank=True, choices=[('1-5', 'Classes 1 to 5'), ('5-10', 'Classes 5 to 10')], max_length=5, null=True),
        ),
    ]
