# Generated by Django 5.1.3 on 2024-11-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='classteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
