# Generated by Django 5.1.3 on 2024-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AlterField(
            model_name='exam',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='users.course'),
        ),
    ]
