# Generated by Django 5.1.3 on 2024-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_disciplinaryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ManyToManyField(related_name='exam_course', to='users.course'),
        ),
    ]
