# Generated by Django 5.1.3 on 2024-12-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_payment_razorpay_payment_id_alter_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
    ]
